### ISSUE TITLE
Strongly typed language variants doesn't include values for Elements

### ISSUE THREAD

**Issue by twadevs** [Kentico/kontent-management-sdk-net#183]
### What I'm trying to do:

Hi,

I'm trying to use the ` .GetLanguageVariantAsync<T>` method to retrieve strongly typed items. It seems to return the Item object (id, etc..) and last updated, etc.., but the Elements are all null. 

Using the LanguageVariantModel without the strongly typed object works fine.

### Repro steps

1. Installed the latest Kentico Model Generator (v7.0.0)
2. Generated models as per documentation
3. Use the `client.GetLanguageVariantAsync<T>` method to retrieve the language variant
4. The returned object doesn't include any values for the Elements

### Expected behaviour

The strongly typed object should include values for the Elements.

### Test environment

 - Platform/OS: .Net 6, Windows

### Screenshots

![image](https://user-images.githubusercontent.com/67626158/174942218-b73a7745-22a4-4e97-98d8-ecdfb6acc584.png)

![image](https://user-images.githubusercontent.com/67626158/174942160-17de75a1-05c5-45af-899e-f25c2000b50e.png)

**Comment by gormal** [comment]
Hi! 

This issue has gone quiet. 👻 

It’s been a while since the last update here. 
If we missed anything on this issue or if you want to keep it open, please reply here.  

Thanks for being a part of the Kontent.ai community!

**Comment by gormal** [comment]
Happy to hear that you were able to find a solution! 

This info could be interesting for @Sevitas

**Comment by Sevitas** [comment]
Hi, 
we have made some improvements in the latest [version](https://github.com/Kentico/kontent-generators-net/releases/tag/7.0.0) of the Generators SDK,  renaming the parameter _--contentmanagementapi_ to _--managementapi_ was one of them. If you need to generate the Management models, you need to use the new parameter, otherwise the default value will be used and Delivery models will be generated. We have created a [feature request](https://github.com/Kentico/kontent-generators-net/issues/154) which should clear up the confusion. 
What do you think about it @twadevs?

**Comment by twadevs** [comment]
> 

Thanks @Sevitas , sounds good. I think an error message would be great.
