### ISSUE TITLE
Is the Kontent Management SDK thread safe?

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-management-sdk-net#51]
### Motivation

I am wondering if this .NET library is thread-safe? I instantiated it as a singleton using .NET Core's out of the box DI registration mechanism and was wondering if that is OK or not.

FYI, this is how I am registering the client in .NET Core. Let me know if this is incorrect:

            var managementOptions = new ManagementOptions();
            Configuration.GetSection("ManagementOptions").Bind(managementOptions);

            services.AddSingleton<ManagementClient>(new ManagementClient(managementOptions));

**Comment by petrsvihlik** [comment]
Hi @xantari ,
the SDK itself does not contain any static state. It also doesn't violate any of Microsoft's [managed threading best practices](https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-threading-best-practices). I think it's actually a good idea to use it as a singleton in order to reuse the `HttpClient`. As the [MS docs](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) say:
> HttpClient is intended to be instantiated once and reused throughout the life of an application.

It could be even better to use the `HttpClientFactory` as suggested in the other [conversation](https://github.com/Kentico/kontent-delivery-sdk-net/issues/182#issuecomment-570083093) of ours.
