### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-management-sdk-net#60]
### Brief bug description

The project used for generating test fixtures (`e38f8e94-7d3b-0062-77f5-a4bc505780d4`) is corrupted (there are some extra items, some items are missing, etc.)

### Repro steps

Just run the unit tests with the `TestRunType.LiveEndPoint_SaveToFileSystem` setting.

### Expected behavior

- fix the data in the project (align them with what the unit tests expect)
- create an export of the data (using KK backup manager) and commit it to this repo so that anybody can back to it later (including the community)
- document the process of regenerating the text fixtures in GH Wiki so that everybody is aware and able to create tests on their own from the export package
- add fixtures for the [new functionality](https://github.com/Kentico/kontent-management-sdk-net/pull/59/files#diff-cf9d19cb7e555fd018fa4c69fe0c69c06cee2fa4dab7bd96c6e8396ad0b275bd)

### Additional context

- part of the currently failing tests might be caused by the upgrade of the test project to .NET 5 (not sure if the fixture generation is agnostic to that)
- MAPI key is newly configurable via user secrets ({"ApiKey":"yourapikey"})

**Comment by makma** [comment]
### Fix the data in the project (align them with what the unit tests expect)
- data isfixed, only small changes namely:
-- different GUIDs for existing taxonomies
-- removed asset directories structure
-- inactive Spanish language
-- some small inconsistencies for the `/validate` endpoint

**Comment by makma** [comment]
The main issue with tests running on mocked data was introduced in https://github.com/Kentico/kontent-management-sdk-net/commit/c516343b by removing the API key. Therefore, the client (even for mocked data) couldn't be initialized properly.

Not sure whether to fix it in the main test class or in the init of the mocked client. I've chosen the `ManagementClientTests.cs` main class since it's IMO more explicit- https://github.com/Kentico/kontent-management-sdk-net/commit/372ca1bd67f0c454d4ae42c30fa662470025de3b.

**Comment by makma** [comment]
**Create an export of the data (using KK backup manager) and commit it to this repo so that anybody can back to it later (including the community)**
- https://github.com/Kentico/kontent-management-sdk-net/commit/e93f6f8eb4da9320c2df26bbb7fb2e2ff22b5020

**Comment by petrsvihlik** [comment]
> Not sure whether to fix it in the main test class or in the init of the mocked client. I've chosen the ManagementClientTests.cs main class since it's IMO more explicit- 372ca1b.
This is ok

**Comment by makma** [comment]
** document the process of regenerating the text fixtures in GH Wiki so that everybody is aware and able to create tests on their own from the export package **
I believe it's more explicit in the readme, but we can discuss it and move it to wiki.

**Comment by makma** [comment]
Moreover, there was another mistake - when using `FileSystemHttpClientMock` with `LiveEndPoint_SaveToFileSystem` mocking logic didn't include headers into the requests, therefore, e.g. requests for paging (with a continuation token) were send without token which caused an infinite loop (keep asking for the `NextPage` without continuation token)- fixed in https://github.com/Kentico/kontent-management-sdk-net/commit/98bfebb46e1bf7618e7a65be51b74b50f93f3a76

**Comment by makma** [comment]
### Add fixtures for the new functionality
- tests added in https://github.com/Kentico/kontent-management-sdk-net/commit/734380b7c6b13459810aa6fd6239219db5d6c84a

### Two tests were marked skipped
- `UpdateContentItem_UsingResponseModel_UpdatesContentItem` since underlying item/logic in Kontent is in inconsistent state and cannot be deleted in UI. This test is very indeterministic, often throwsKentico.Kontent.Management.Exceptions.ManagementException : The request was not processed because the specified object has been modified by another request.: `. Since it's out of the scope of this task - suggested solution is to recreate/create new the `Hooray!` item in tests and Kontent project, as well.
- `ListFolders_GetFolderHierarchy_ExistingFolder` - test is failing, moreover, there are IMO some issues with the logic of the tested method, namely:
-- What's the expected output?
-- Why does `GetFolderHierarchy` method returns IEnumerable<AssetFolderHierarchy> instead of  AssetFolderHierarchy?
-- What's the difference between `GetParentLinkedFolderHierarchyById` and `GetFolderHierarchy`?
-- Why `if (itm.Folders != null)` and not `(itm.Folders.Count > 0)` ?
-- Method is not returning correct hierarchy (failing assert, returns null)
-- Insufficient comment

**Comment by petrsvihlik** [comment]
`UpdateContentItem_UsingResponseModel_UpdatesContentItem` - agreed

`ListFolders_GetFolderHierarchy_ExistingFolder` - @xantari could you please take a look at the following TODOs and resolve them? we need to make sure the comments are clear and the logic robust before we release a production version.

https://github.com/Kentico/kontent-management-sdk-net/blob/1e3ffa91e2ed6b290d79f7778490e287f7191f5a/Kentico.Kontent.Management.Tests/ManagementClientTests.cs#L1064-L1069

**Comment by petrsvihlik** [comment]
+ I'm also wondering if it'd be possible to somehow unify the `AssetFolderLinkingHierarchy` and `AssetFolderHierarchy` models (if not the methods they're used in).

**Comment by xantari** [comment]
@petrsvihlik Looking at this now. In regards to the AssetFolderLinkingHierarchy, I split it out because I wasn't sure if / when you get to the point of adding the function to add folders whether or not you wanted that Parent folder linking. Would the programmer know they could leave that null since it doesn't map to anything in the management API? Or would they think they need to fetch that parent folder and pass it in before submitting it to the "Add Asset Folders" API endpoint?

https://docs.kontent.ai/reference/management-api-v2#operation/add-asset-folders

**Comment by xantari** [comment]
@petrsvihlik Is there something I need to do to run the unit tests?

Getting this when running the ListFolders_GetFolderHierarchy_ExistingFolder unit test (haven't touched anything in the code yet, running a fresh version of your repo after bringing in your upstream changes)

```
Cannot find expected data folder C:\TFS\kontent-management-sdk-net\Kentico.Kontent.Management.Tests\bin\Debug\net5.0\Data\ListFolders_Qjuq0PLi1K\GET_7NAVt53LQk for GET request to https://manage.kontent.ai/v2/projects/e38f8e94-7d3b-0062-77f5-a4bc505780d4/folders. 
Either the request properties or content seem to differ from the expected recorded state.
Request:
{
  "Version": "1.1",
  "VersionPolicy": 0,
  "Content": null,
  "Method": {
    "Method": "GET"
  },
  "RequestUri": "https://manage.kontent.ai/v2/projects/{PROJECT_ID}/folders",
  "Headers": [
    {
      "Key": "Authorization",
      "Value": [
        "Bearer {API_KEY}"
      ]
    },
    {
      "Key": "X-KC-SDKID",
      "Value": [
        "nuget.org;Kentico.Kontent.Management;{SDK_ID}"
      ]
    }
  ],
  "Properties": {},
  "Options": {}
}
Request content:

Expected: True
Actual:   False'
```

**Comment by xantari** [comment]
@petrsvihlik Here are my responses:

            // TODO: why method returns IEnumerable<AssetFolderHierarchy> ?

When you get a response back from the API it comes in the form of a single AssetFolderHierarchy model. In that model is the Folders property which is IEnumerable<AssetFolderHierarchy>.

That helper method converts an IEnumerable<AssetFolderHiearchy> into IEnumerable<AssetFolderLinkingHiearchy>.

Perhaps a better way to do it is something like this which removes the IEnumerables (haven't tested this):

```
\\NOTE: I also made the Folders a List<AssetFolderLinkingHierarchy> so I could have the .Add() method on the collection.

public static AssetFolderLinkingHierarchy GetParentLinkedFolderHierarchyV2(this AssetFolderHierarchy folders,
AssetFolderLinkingHierarchy parentLinked = null)
    {
        // Recursively search for the folder hierarchy that an asset is in. Returns null if file is not in a folder.
        var folderList = new AssetFolderLinkingHierarchy();
        folderList.Folders = new List<AssetFolderLinkingHierarchy>();
        foreach (var itm in folders.Folders)
        {
            var newFolder = new AssetFolderLinkingHierarchy()
            {
                ExternalId = itm.ExternalId,
                Folders = (itm.Folders != null && itm.Folders.Count() > 0) ? new List<AssetFolderLinkingHierarchy>() : null,
                Id = itm.Id,
                Name = itm.Name
            };
            if (itm.Folders != null)
            {
                newFolder.Folders = itm.GetParentLinkedFolderHierarchyV2(newFolder)?.Folders;
            }
            if (parentLinked != null)
            {
                newFolder.Parent = parentLinked;
            }
            folderList.Folders.Add(newFolder);
        }
        return folderList;
    }
```

            // TODO: GetParentLinkedFolderHierarchyById vs GetFolderHierarchy difference?

Once you have called GetParentLinkedFolderHierarchy to retrieve the IEnumerable<AssetFolderLinkingHierarchy> from an IEnumerable<AssetFolderHierarchy> which basically makes the entire recursive folder tree have Parent links (so you can walk back up the tree) you can then call GetParentLinkedFolderHiearchyById to narrow in on a folder tree where a particular folder exists.

Example:

```
Root
  \Folder1 (id #1)
      \SubFolder1 (id #4)
  \Folder2 (id #2)
      \SubFolder2 (id #5)
      \SubFolder3 (id #6)
           \SubFolder4 (id #7)
  \Folder3 (id #3)
       \SubFolder5 (id #8)
```

If I get an asset back from Kentico Kontent. And lets say the Asset's folder ID came back as the number 6. If I wanted to know the full nested folder structure that Asset is contained in that helper method will tell me.

So in this example I would do the following (where model is the root node):

model.Folders.GetParentLinkedFolderHiearchyById(6)

Which would return a AssetFolderLinkingHierachy model at this level: \SubFolder3. And since it has a parent link you can then walk up the tree if you wanted to. If the parent link was not there you could only walk down the tree (to SubFolder4 (ID #7))

The whole reason I needed this parent linking stuff was to know what the full nested subfolder an asset was located in. Cause I needed to filter out specific folders from my search results.

This is another method which could be updated as follows (where you get rid of the IEnumerable bits)

```
public static AssetFolderLinkingHierarchy GetParentLinkedFolderHierarchyById(this AssetFolderLinkingHierarchy folders, string folderId)
    {
        if (folders == null)
        {
            return null;
        }
        foreach (var folder in folders.Folders)
        {
            if (folder.Id == folderId)
            {
                return folder;
            }
            else if (folder.Folders != null && folder.Folders.Count() > 0)
            {
                var nestedFolder = folder.Folders.GetParentLinkedFolderHierarchyById(folderId);
                if (nestedFolder != null)
                {
                    return nestedFolder;
                }
            }
        }
        return null;
    }
```

            // TODO: Why `if (itm.Folders != null)` and not `(itm.Folders.Count > 0)` ?

I think your refering to this line:

Folders = (itm.Folders != null && itm.Folders.Count() > 0) ? new List<AssetFolderLinkingHierarchy>() : null,

It's probably not needed if the API always returns null instead of an empty collection.

            // TODO: Method is not returning correct hierarchy

Can't test this right now. Need help (see previous comment)

            // TODO: insufficient comment

Not sure what else to add?

**Comment by makma** [comment]
> @petrsvihlik Here are my responses:
> 
> ```
>         // TODO: why method returns IEnumerable<AssetFolderHierarchy> ?
> ```
> 
> When you get a response back from the API it comes in the form of a single AssetFolder model. In that model is the Folders property which is IEnumerable<AssetFolderHierarchy>.
> 
> That helper method converts an IEnumerable<AssetFolderHiearchy> into IEnumerable<AssetFolderLinkingHiearchy>.
> 
> ```
>         // TODO: GetParentLinkedFolderHierarchyById vs GetFolderHierarchy difference?
> ```
> 
> Once you have called GetParentLinkedFolderHierarchy to retrieve the IEnumerable<AssetFolderLinkingHierarchy> from an IEnumerable<AssetFolderHierarchy> which basically makes the entire recursive folder tree have Parent links (so you can walk back up the tree) you can then call GetParentLinkedFolderHiearchyById to narrow in on a folder tree where a particular folder exists.
> 
> Example:
> 
> ```
> Root
>   \Folder1 (id #1)
>       \SubFolder1 (id #4)
>   \Folder2 (id #2)
>       \SubFolder2 (id #5)
>       \SubFolder3 (id #6)
>            \SubFolder4 (id #7)
>   \Folder3 (id #3)
>        \SubFolder5 (id #8)
> ```
> 
> If I get an asset back from Kentico Kontent. And lets say the Asset's folder ID came back as the number 6. If I wanted to know the full nested folder structure that Asset is contained in that helper method will tell me.
> 
> So in this example I would do the following (where model is the root node):
> 
> model.Folders.GetParentLinkedFolderHiearchyById(6)
> 
> Which would return a AssetFolderLinkingHierachy model at this level: \SubFolder3. And since it has a parent link you can then walk up the tree if you wanted to. If the parent link was not there you could only walk down the tree (to SubFolder4 (ID #7))
> 
> The whole reason I needed this parent linking stuff was to know what the full nested subfolder an asset was located in. Cause I needed to filter out specific folders from my search results.
> 
> ```
>         // TODO: Why `if (itm.Folders != null)` and not `(itm.Folders.Count > 0)` ?
> ```
> 
> I think your referring to this line:
> 
> Folders = (itm.Folders != null && itm.Folders.Count() > 0) ? new List() : null,
> 
> It's probably not needed if the API always returns null instead of an empty collection.
> 
> ```
>         // TODO: Method is not returning correct hierarchy
> ```
> 
> Can't test this right now. Need help (see previous comment)
> 
> ```
>         // TODO: insufficient comment
> ```
> 
> Not sure what else to add?

Hey @xantari!
It's nice to virtually meet. I fetched a fresh master and can confirm I can not run the test successfully on my machine, as well. I'm working on fix. I'll keep you updated as soon as possible.

**Comment by makma** [comment]
Oh, I got it now, the mac issue is just a separate one :/. From the log, I noticed you are running on the Win environment. The mocked data for skipped tests were not included in the original PR. I'm going to populate those data and add them. I'll keep you update.

**Comment by makma** [comment]
Missing mocked data should be fixed in https://github.com/Kentico/kontent-management-sdk-net/pull/63

**Comment by petrsvihlik** [comment]
> @petrsvihlik Looking at this now. In regards to the AssetFolderLinkingHierarchy, I split it out because I wasn't sure if / when you get to the point of adding the function to add folders whether or not you wanted that Parent folder linking. Would the programmer know they could leave that null since it doesn't map to anything in the management API? Or would they think they need to fetch that parent folder and pass it in before submitting it to the "Add Asset Folders" API endpoint?
> 
> https://docs.kontent.ai/reference/management-api-v2#operation/add-asset-folders

good point, let's leave it this way

**Comment by petrsvihlik** [comment]
> // TODO: why method returns IEnumerable<AssetFolderHierarchy> ?
But when you search for a given `string folderId`...shouldn't it return only a single `AssetFolderHierarchy`?

**Comment by xantari** [comment]
> > // TODO: why method returns IEnumerable ?
> > But when you search for a given `string folderId`...shouldn't it return only a single `AssetFolderHierarchy`?

Yes, let me fix that.

**Comment by xantari** [comment]
Sorry, I had a packed day yesterday, so wasn't able to work on this till this morning.

**Comment by petrsvihlik** [comment]
the only outstanding issue was split into #66
